apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm-clis
  namespace: ohmyfans
  labels:
    app: dtm-clis
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: dtm-clis
  template:
    metadata:
      labels:
        app: dtm-clis
    spec:
      serviceAccountName: ohmyfans-discovery
      containers:
      - name: dtm-clis
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      imagePullSecrets:
      - name: pull-secret
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
apiVersion: v1
kind: Service
metadata:
  name: dtm-clis
  namespace: ohmyfans
spec:
  selector:
    app: dtm-clis
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32015
  type: NodePort
